server:
  port: 19580

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
    open-in-view: true
  datasource:
    url: jdbc:postgresql://postgres:5432/bachelors-thesis
    username: postgres
    password: admin
    platform: postgres
    hikari:
      max-lifetime: 300000
      idle-timeout: 300000
      connection-timeout: 30000
    dbcp2:
      test-while-idle: true
      test-on-borrow: true
lifespanInHours: 24
secret: "some random string"
tokenServerUrl: "http://bt-tokenizer:19575"
