spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bachelors-thesis
tokenServerUrl: "http://localhost:19575"
backendServerUrl: "http://localhost:19580"
staticFilePath: "images/"
empathyServerUrl: "http://localhost:8080"
frontendUrl: "http://localhost:4200"

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: FULL
