server:
  port: 19580

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
    open-in-view: true
  datasource:
    url: jdbc:postgresql://postgres:5432/bachelors-thesis
    username: postgres
    password: admin
    platform: postgres
    hikari:
      max-lifetime: 300000
      idle-timeout: 300000
      connection-timeout: 30000
    dbcp2:
      test-while-idle: true
      test-on-borrow: true
  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    properties:
      mail:
        debug: false
        transport:
          protocol: smtp
        smtp:
          port: 587
          auth: true
          starttls:
            enable: true

    username: webappbt@gmail.com
    password: yygcnjvxivmwokzj

lifespanInHours: 2400
secret: "some random string"
tokenServerUrl: "https://bt-tokenizer.sudo.rocks"
empathyServerUrl: "https://bt-empathy.sudo.rocks"
backendServerUrl: "https://bt-backend.sudo.rocks"
frontendUrl: "https://bt-webapp.sudo.rocks"
staticFilePath: ""

